CREATE DATABASE EventyDB;
GO
USE EventyDB;
GO

CREATE TABLE Users(
    Id INT NOT NULL IDENTITY(10000, 1),
    FirstName NVARCHAR(255) NOT NULL,
	LastName NVARCHAR(255) NOT NULL,
    BirthDate DATE NOT NULL,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    Pass NVARCHAR(255) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    PhoneNumber NVARCHAR(255) NOT NULL,
    IsAdmin BIT NOT NULL,
    ProfileImage NVARCHAR(255) NOT NULL DEFAULT 'default_pfp.jpg'
);

ALTER TABLE
    Users ADD CONSTRAINT Users_Id_PK PRIMARY KEY(Id);

CREATE TABLE Place(
    Id INT NOT NULL IDENTITY(10000, 1),
    OwnerId INT NOT NULL,
    PlaceType INT NOT NULL,
    TotalOccupancy INT NOT NULL,
    Summary NVARCHAR(255) NOT NULL,
    PlaceAddress NVARCHAR(255) NOT NULL,
    Apartment INT NOT NULL,
    City NVARCHAR(255) NOT NULL,
    Zip INT NOT NULL,
    Country NVARCHAR(255) NOT NULL,
    Price INT NOT NULL,
    PlaceImage1 NVARCHAR(255) NOT NULL DEFAULT 'default_pl.jpg',
    PlaceImage2 NVARCHAR(255) NOT NULL DEFAULT 'default_pl.jpg',
    PlaceImage3 NVARCHAR(255) NOT NULL DEFAULT 'default_pl.jpg',
    PlaceImage4 NVARCHAR(255) NOT NULL DEFAULT 'default_pl.jpg',
    PlaceImage5 NVARCHAR(255) NOT NULL DEFAULT 'default_pl.jpg',
    PlaceImage6 NVARCHAR(255) NOT NULL DEFAULT 'default_pl.jpg',  
    PublishedAt DATETIME NOT NULL DEFAULT GETDATE(),
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE()
);
ALTER TABLE
    Place ADD CONSTRAINT Place_Id_PK PRIMARY KEY(Id);
CREATE TABLE Orders(
    Id INT NOT NULL IDENTITY(10000, 1),
    UserId INT NOT NULL,
    PlaceId INT NOT NULL,
    StartDateAndTime DATETIME NOT NULL DEFAULT GETDATE(),
    EndDateAndTime DATETIME NOT NULL DEFAULT GETDATE(),
    Price INT NOT NULL,
    Total INT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    ExtraId INT NOT NULL
);
ALTER TABLE
    Orders ADD CONSTRAINT Orders_Id_PK PRIMARY KEY(Id);
CREATE TABLE ReviewsMedia(
    Id INT NOT NULL IDENTITY(10000, 1),
    ReviewId INT NOT NULL,
    FilePath NVARCHAR(255) NOT NULL,
    MimeType NVARCHAR(255) NULL
);
ALTER TABLE
    ReviewsMedia ADD CONSTRAINT ReviewsMedia_Id_PK PRIMARY KEY(Id);
CREATE TABLE Reviews(
    Id INT NOT NULL IDENTITY(10000, 1),
    OrderId INT NOT NULL,
    UserId INT NOT NULL,
    Rating INT NOT NULL,
    Comment NVARCHAR(255) NOT NULL
);
ALTER TABLE
    Reviews ADD CONSTRAINT Reviews_Id_PK PRIMARY KEY(Id);
CREATE TABLE OrderExtras(
    Id INT NOT NULL IDENTITY(10000, 1),
    ExtraType NVARCHAR(255) NOT NULL,
    Price INT NOT NULL
);
ALTER TABLE
    OrderExtras ADD CONSTRAINT OrderExtras_Id_PK PRIMARY KEY(Id);
CREATE TABLE PlaceMedia(
    Id INT NOT NULL IDENTITY(10000, 1),
    PlaceId INT NOT NULL,
    PlaceType NVARCHAR(255) NOT NULL,
    FilePath NVARCHAR(255) NOT NULL,
    MimeType NVARCHAR(255) NULL
);
ALTER TABLE
    PlaceMedia ADD CONSTRAINT PlaceMedia_Id_PK PRIMARY KEY(Id);
CREATE TABLE Message(
    Id INT NOT NULL IDENTITY(10000, 1),
    MessageText NVARCHAR(255) NOT NULL,
    WhenSent DATETIME NOT NULL DEFAULT GETDATE(),
    UserId INT NOT NULL,
    ChatId INT NOT NULL
);
ALTER TABLE
    Message ADD CONSTRAINT Message_Id_PK PRIMARY KEY(Id);
CREATE TABLE Chat(
    Id INT NOT NULL IDENTITY(10000, 1),
    SellerId INT NOT NULL,
    BuyerId INT NOT NULL
);
ALTER TABLE
    Chat ADD CONSTRAINT Chat_Id_PK PRIMARY KEY(Id);
CREATE TABLE Receipts(
    Id INT NOT NULL IDENTITY(10000, 1),
    OrderId INT NOT NULL,
    CustomerId INT NOT NULL,
    PaymentDate DATE NOT NULL,
    Amount INT NOT NULL,
    HoursBooked INT NOT NULL
);
ALTER TABLE
    Receipts ADD CONSTRAINT Receipts_Id_PK PRIMARY KEY(Id);
CREATE TABLE HouseBackyard(
    Id INT NOT NULL IDENTITY(10000, 1),
    HasPool BIT NOT NULL,
    HasBbq BIT NOT NULL,
    HasHotub BIT NOT NULL,
    HasTables BIT NOT NULL,
    HasChairs BIT NOT NULL
);
ALTER TABLE
    HouseBackyard ADD CONSTRAINT HouseBackyard_Id_PK PRIMARY KEY(Id);
CREATE TABLE Hall(
    Id INT NOT NULL IDENTITY(10000, 1),
    HasTables BIT NOT NULL,
    HasChairs BIT NOT NULL,
    HasSpeakerAndMic BIT NOT NULL,
    HasProjector BIT NOT NULL,
    HasBar BIT NOT NULL
);
ALTER TABLE
    Hall ADD CONSTRAINT Hall_Id_PK PRIMARY KEY(Id);
CREATE TABLE PrivateHouse(
    Id INT NOT NULL IDENTITY(10000, 1),
    HasSpeakerAndMic BIT NOT NULL,
    HasAirConditioner BIT NOT NULL,
    HasTv BIT NOT NULL,
    HasWaterHeater BIT NOT NULL,
    HasCoffeeMachine BIT NOT NULL
);
ALTER TABLE
    PrivateHouse ADD CONSTRAINT PrivateHouse_Id_PK PRIMARY KEY(Id);
CREATE TABLE Apartment(
    Id INT NOT NULL IDENTITY(10000, 1),
    HasSpeakerAndMic BIT NOT NULL,
    HasAirConditioner BIT NOT NULL,
    HasTv BIT NOT NULL,
    HasWaterHeater BIT NOT NULL,
    HasCoffeeMachine BIT NOT NULL
);
ALTER TABLE
    Apartment ADD CONSTRAINT Apartment_Id_PK PRIMARY KEY(Id);
CREATE TABLE UserAuthToken(
    UserID INT NOT NULL,
    AuthToken NVARCHAR(255) NOT NULL
);
ALTER TABLE
    UserAuthToken ADD CONSTRAINT PK_UserAuthToken_AuthToken PRIMARY KEY(AuthToken);



ALTER TABLE
    Orders ADD CONSTRAINT Orders_UserId_FK FOREIGN KEY(UserId) REFERENCES Users(Id);
ALTER TABLE
    Place ADD CONSTRAINT Place_OwnerId_FK FOREIGN KEY(OwnerId) REFERENCES Users(Id);
ALTER TABLE
    Orders ADD CONSTRAINT Orders_PlaceId_FK FOREIGN KEY(PlaceId) REFERENCES Place(Id);
ALTER TABLE
    Reviews ADD CONSTRAINT Reviews_OrderId_FK FOREIGN KEY(OrderId) REFERENCES Orders(Id);
ALTER TABLE
    ReviewsMedia ADD CONSTRAINT ReviewsMedia_ReviewId_FK FOREIGN KEY(ReviewId) REFERENCES Reviews(Id);
ALTER TABLE
    Orders ADD CONSTRAINT Orders_ExtraId_FK FOREIGN KEY(ExtraId) REFERENCES OrderExtras(Id);
ALTER TABLE
    PlaceMedia ADD CONSTRAINT PlaceMedia_PlaceId_FK FOREIGN KEY(PlaceId) REFERENCES Place(Id);
ALTER TABLE
    Message ADD CONSTRAINT Message_ChatId_FK FOREIGN KEY(ChatId) REFERENCES Chat(Id);
ALTER TABLE
    Chat ADD CONSTRAINT Chat_SellerId_FK FOREIGN KEY(SellerId) REFERENCES Users(Id);
ALTER TABLE
    Chat ADD CONSTRAINT Chat_BuyerId_FK FOREIGN KEY(BuyerId) REFERENCES Users(Id);
ALTER TABLE
    Receipts ADD CONSTRAINT Receipts_OrderId_FK FOREIGN KEY(OrderId) REFERENCES Orders(Id);
ALTER TABLE
    Receipts ADD CONSTRAINT Receipts_CustomerId_FK FOREIGN KEY(CustomerId) REFERENCES Users(Id);
ALTER TABLE
    UserAuthToken ADD CONSTRAINT FK_UserAuthToken_AccountID FOREIGN KEY(UserID) REFERENCES Users(ID);
    

    
 

    
